export const NAME_IS_WHITE_TEXT = [
  'rosybrown',
  'red',
  'saddlebrown',
  'coral',
  'orange',
  'brown',
  'goldenrod',
  'olivegreen',
  'darkolivegreen',
  'seagreen',
  'lightsea',
  'teal',
  'cadetblue',
  'pastelblue',
  'mediumslateblue',
  'bluedark',
  'navy',
  'rebeccapurple',
  'purple',
  'vividorchid',
  'darkmagenta',
  'deepmagenta',
  'fuchsia',
  'violetred',
  'pink',
  'vibrantpink',
  'paleredviolet',
  'carmine',
  'wine',
];

export const MEETING_COLORS = {
  turquoise: '#31E0B0',
  orange: '#FF5E10',
  blue: '#00ABF7',
  pink: '#FF00BB',
  purple: '#9C29FF',
  green: '#6FDD00',
  red: '#E30000',
  bluedark: '#304AFF',
  pinklight: '#FF89C4',
  purplelight: '#D597FF',
  greenlight: '#C6EC5C',
  orangelight: '#FFA115',
  bluelight: '#75DEFE',
  redlight: '#FAA291',
  brown: '#BB813F',
  yellow: '#FFEF33',
  olivegreen: '#93A000',
  lightyellow: '#FAE391',
  violetred: '#C03FA3',
  rosybrown: '#B58787',
  cadetblue: '#2095BB',
  lightsteelblue: '#ABB5FF',
  seagreen: '#04B45F',
  palegreen: '#8DE990',
  saddlebrown: '#964C42',
  pastelblue: '#77A1CC',
  palesilver: '#D2BABA',
  coral: '#DF6B6B',
  bisque: '#FFD9C4',
  goldenrod: '#DAA520',
  tan: '#D2BD93',
  darkolivegreen: '#536C27',
  mint: '#ADE6DF',
  lightsea: '#45AFAA',
  teal: '#036E6E',
  wine: '#760040',
  cyan: '#00FFFF',
  mediumslateblue: '#6674D7',
  navy: '#0013BB',
  rebeccapurple: '#663399',
  vividorchid: '#D429FF',
  darkmagenta: '#810E81',
  deepmagenta: '#C303C6',
  fuchsia: '#FA00FF',
  lavendermagenta: '#EE82EE',
  thistle: '#EEB4DD',
  vibrantpink: '#FF007A',
  cottoncandy: '#FFC0DE',
  paleredviolet: '#D96598',
  carmine: '#B50A52',
  gray: '#878291',
};

export const MEETING_COLORS_ARRAY = Object.values(MEETING_COLORS);
export const MEETING_COLORS_KEYS = Object.keys(MEETING_COLORS);
